ktor:
    application:
        modules:
            - com.leafy.ApplicationKt.module
    deployment:
        port: 8080

postgres:
    url: "jdbc:postgresql://mumkifseskit.beget.app:5432/default_db?targetServerType=master&ssl=false&sslmode=disable"
    user: "cloud_user"
    password: "R1*WAICuG63O"

